[WIP] Restructure project in multiple crates
z2oh/sexe pull request #36
Opened 2018-11-01 00:34 UTC by Istar-Eldritch

This is a work in progress PR.

@z2oh So far I just created a multiple crate structure. After checking the source code I believe it's already well structure enough as to do the complete restructure in this single PR. I'll structure the restructure of the different parts in independent commits to simplify its review.

Let me know if this is something you disagree with. I plan to start working on such refactor tomorrow evening UTC time.

2018-11-01 18:59 UTC, z2oh commented
I was thinking more along the lines of having the root crate be the interface, and then the expression and parser libraries being sub crates. I believe this is along the same lines as [ripgrep](https://github.com/BurntSushi/ripgrep)'s organization, but admittedly I do not know which way will work best :)

Ideally, I want to be able to type `cargo run` at the _root_ directory and have it run. If the organizational strategy proposed in this PR accomplishes that, then it is fine with me :)

2018-11-01 20:43 UTC, Istar-Eldritch commented
It was doing that, but I agree. Let's do it as you advise. :wink:

2018-11-01 21:59 UTC, Istar-Eldritch commented
@z2oh the main changes are done. 

There is a flag I would like to raise regarding [`nom` public export](https://github.com/z2oh/sexe/pull/36/files#diff-fc7ff63890d2ac626ab17a006fa4fb40R5) from the parser crate. This, while handy has some serious drawbacks regarding maintainability and suppor of the crate interface. For example, if the nom developers decide to change this type in the future the `sexe_parser` crate will be forced to update it's interface too, making it hightly coupled to `nom`. This is probably a discussion for another time so I just wanted to mention ensure awareness.

2018-11-01 22:03 UTC, Istar-Eldritch commented
Also, I just realised it now by looking at the diff. I use an automatic `fmt` and forced the standard style in all the files I touched :confounded: . Let me know if this is an issue and I'll recover them to their previous state.

2018-11-02 23:04 UTC, z2oh requested changes
Don't worry about rustfmt, it needs to be done sooner or later 🙂

Would you mind moving the `evaluate_function_over_domain` function to the expression crate? Thanks for rearchitecting this, awesome work!! 😀

2018-11-02 23:04 UTC, z2oh commented on src/interface.rs
> +fn evaluate_function_over_domain(
Could you possibly refactor this function as part of the rearchitecture?

This function makes the most sense to be a publicly exported function in the `sexe_expression` crate. We should also change this from taking `function_string` to an actual expression node. This means that where we call this function, we will need to first parse the function string, then pass the expression node to _this_ function in the expression module.

2018-11-02 23:07 UTC, z2oh commented
We can fix the coupling with nom by adding a function to the `parser` crate which takes a `&str` and returns an `ExpressionNode`. This way we won't need to deal with `CompleteStr` except for inside the `parser` crate. This changes goes hand in hand with the change I requested above about moving the `evaluate_function_over_domain` function to the `expression` crate.

If we do that, we should be able to remove the re-export of `CompleteStr` right?

2018-11-20 06:30 UTC, merged

2018-11-20 06:30 UTC, z2oh commented
Closed via #37

2018-11-24 13:03 UTC, Istar-Eldritch commented
Damn, sorry @z2oh I completely forgot about this.

2018-11-27 18:18 UTC, z2oh commented
No problem @Istar-Eldritch ! Thanks for doing the legwork on this! 😀